### ISSUE TITLE
SCREEN_ID

### ISSUE THREAD

**Issue by Yotaz** [CBiX/gotubecast#3]
Hello,

First, thanks for this project, it's great !

It it probably very simple, but I try to set the SCREEN_ID in the file RASPI.SH by setting the SCREEN_ID variable at the beginning of the mentionned file in the EXPORT section but I have this error.

ex:
export SCREEN_ID="123-456-789-123"

Do I have to include the "-" characters ?

If I do not set the SCREEN-ID, all are working fine...

Error:
panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
main.main()
        /usr/local/go/gotubecast/main.go:116 +0x18c4

		THanks !

**Comment by cbix** [comment]
Hi,

What you are trying to set as the screen ID is actually the pairing code. Run gotubecast without any parameters and you should get a screen ID in the first line, it's something like "cpsja6opmlbgkkvotb4dvfeb25".

Good luck!

**Comment by Yotaz** [comment]
Great !!! It's working very fine now :) Thanks for the quick answer !

Do you know if there is a chance the ~10 sec lag will be fixed when we select a new video  ?

Thanks again !

**Comment by cbix** [comment]
The huge delay comes from youtube-dl, which is responsible for getting the video stream URL for a given video ID.

Only way to make it faster is to replace youtube-dl with a faster tool, make youtube-dl faster or integrate the functionality in gotubecast, which would be quite some work. Another reason for using youtube-dl is because it's well maintained and gets updated quickly when APIs change etc. ;)

**Comment by Yotaz** [comment]
Great, thank you very much !

**Comment by wudthipong** [comment]
thanks for this project.
I have a question. Can I set a screen ID to be unchanged (fixed) every time I run or reboot?

I try to set the SCREEN_ID in the file RASPI.SH 
with **export SCREEN_ID="123456789123"** <--- pairing code from first run.
but pairing code changed every time to run or reboot

thanks

**Comment by cbix** [comment]
I think my comment above ( https://github.com/CBiX/gotubecast/issues/3#issuecomment-293614866 ) answers this. Screen ID is fixed an can be set with the -s flag. Pairing code changes every ~ 5 minutes, which can not be influenced, but it might actually prevent people from hacking your youtube ;)

**Comment by wudthipong** [comment]
Thank you for answer
I'm confused between SCREEN_ID and pairing code, which after reading your answer
I understand that it is different and requires pairing with the code every time when rebooting.

I understand this is correct?

However, what you do is very useful for me. Thank you.

**Comment by cbix** [comment]
There are 3 different entities envolved in a setup:
* the YouTube **server**
* the **screen** (here, gotubecast is managing the connection between the screen and the YouTube server)
* **clients** (e.g. Android app, to remote control the screen)

Technically, the **screen** and the **clients** only connect to the YouTube **server**, but after pairing you have a virtual connection between the **client** and the **screen**.

Every **screen** has a screen_id, which can be generated once (by simply running `gotubecast`) and reused later on (by running `gotubecast -s asdf...`). Because the screen ID is very long and complex, YouTube uses pairing codes to connect **clients** to **screens**. As these are rather short and simple (12 digits, easy to enter on a smartphone), they are changing very often, even when the screen is running normally, but this doesn't affect the usability, because you only need the pairing code to **pair** the **client** and the **screen**. After pairing, you don't need to pair again (even when you reboot the **screen**), as long as you use the same screen ID.

I can understand that this isn't very intuitive with gotubecast, because of its text based command line nature. I hope people create nice graphical UIs on top of it 😍
